### ISSUE TITLE
Require cursive version <= 0.12

### ISSUE THREAD

**Issue by Baranowski** [BonsaiDen/cursive_tree_view#15]
Apparently cursive_tree_view no longer works with cursive v. 0.13 because the ViewWrapper trait is not implemented. I will probably get around to fixing it myself at some point, but a short-term workaround would be to update the README and perhaps cargo.toml.

**Comment by gyscos** [comment]
Ah yes, it hadn't been updated to cursive 0.13.
Just published version 0.5.0 which works with cursive 0.13.
